### ISSUE TITLE
"Open in Colab" template

### ISSUE THREAD

**Issue by ikanago** [Qulacs-Osaka/python-project-template#18]
GitHub 上の Jupyter Notebook を [Google Colab で開く静的なリンクを作れる](https://qiita.com/peaceiris/items/4761b200eae6c7fb0e66)らしいので，ビルドするだけでページにそれが挿入されるようにしたいです．

**Comment by ikanago** [comment]
[Colab へのリンクの生成処理](https://github.com/executablebooks/sphinx-book-theme/blob/519cf7c78c9ecffdd073be680af8f8f60bb0b130/sphinx_book_theme/launch.py?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L39) で以下の関数を呼んでいるのですが，`app.env.metadata[pagename]` が `{}` なのでこれは None を返します．
そして呼び出し元の if 文の条件が `False` になり，それ以降処理が行われずに終了してしまいます．
```python
def _is_notebook(app, pagename):
    return app.env.metadata[pagename].get("kernelspec")
```

**Comment by ikanago** [comment]
nb_sphinx ではなく myst_nb を使うとリンクが生成できた

**Comment by Hiroya-W** [comment]
> [Colab へのリンクの生成処理](https://github.com/executablebooks/sphinx-book-theme/blob/519cf7c78c9ecffdd073be680af8f8f60bb0b130/sphinx_book_theme/launch.py?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L39) で以下の関数を呼んでいるのですが，`app.env.metadata[pagename]` が `{}` なのでこれは None を返します． そして呼び出し元の if 文の条件が `False` になり，それ以降処理が行われずに終了してしまいます．
> 
> ```python
> def _is_notebook(app, pagename):
>     return app.env.metadata[pagename].get("kernelspec")
> ```

少し見ていたのですが、この方法は、Markdownで記述されたドキュメントから生成する方法で、Markdownのメタデータ記法で書かれた部分が必要になるので、処理が進まなくなる、という感じだったんですね。
