### ISSUE TITLE
これをテンプレート元にしたときのライセンス

### ISSUE THREAD

**Issue by WATLE** [Qulacs-Osaka/python-project-template#24]
新たなプロジェクトにMIT ライセンスのファイルが残るけど、これをもとにした新しいプロジェクトはMITである必要がある？

**Comment by WATLE** [comment]
調べたところ、そんなことはないみたい
新たなプロジェクトにライセンスファイルが残らないようにできますか？

**Comment by ikanago** [comment]
単にライセンスのファイルを消せば，少なくともそのファイルがないコミットを利用するぶんにはライセンスが問題にならないと思います．
ただ他の人に再利用してもらう場合は，利用方法(改変・商用利用など)を判断してもらうために何らかのライセンスを設定しておくべきだとは思います．

**Comment by Hiroya-W** [comment]
プライベートな環境や個人利用する場合は、ライセンスは気にする必要は無いと思います。
ですが、公開する場合はikanagoさんの言っているように、何かライセンスをつけておく必要がありそうです。
元のライセンスを消すのは良くない（特にMITは著作権を主張しているライセンスです）のと、改変した部分に関しては、MITより強いライセンスを適用しても良いため、利用者で対応してもらうのが良さそうです。

**Comment by Hiroya-W** [comment]
このissueは閉じることにします
