### ISSUE TITLE
pythonのバージョン上限を指定しないとnumpyが入らない

### ISSUE THREAD

**Issue by KowerKoint** [Qulacs-Osaka/python-project-template#27]
僕の環境ではここでエラーが出ました。

```For numpy, a possible solution would be to set the `python` property to ">=3.8,<3.11"```
と書いてあったので`pyproject.toml`の
`python = "^3.8"`を
`python = ">=3.8,<3.11"`
に変更することでnumpyを入れることができました。（WA_TLEさんも同様のことがあったようです。https://fujii-lab-osaka.slack.com/archives/G01DGGCM4Q4/p1634641094074300）

_Originally posted by @herring101 in https://github.com/Qulacs-Osaka/qulacs-developer-docs/pull/8#discussion_r764501355_

↑のように、numpyやscipyなど一部のパッケージでは`<3.11`のような上限を指定しているようです。

**Comment by kotamanegi** [comment]
numpyやscipyはPython 3.11に対応しておらず、最大でもPython3.10までとなっています。
qulacsやqulacs-osakaも同様の仕組みになっているので、Python3.9 or Python 3.10を明示的に指定するのが良いと思います。
