### ISSUE TITLE
Dockerfile内の `POETRY_HOME` について

### ISSUE THREAD

**Issue by Hiroya-W** [Qulacs-Osaka/python-project-template#40]
https://github.com/Qulacs-Osaka/python-project-template/blob/c7578a46207956e8b2066bc9bbf364d715d1efed/.devcontainer/Dockerfile#L6

`POETRY_HOME=/home/vscode/.local` にしているけど、これあまり良くないかもしれないと思っています。

```
vscode ➜ ~/.local $ ls -la
total 20
drwxr-xr-x 4 root   root   4096 Oct  4 06:03 .
drwxr-xr-x 1 vscode vscode 4096 Oct  4 06:16 ..
-rw-r--r-- 1 root   root      5 Oct  4 06:03 VERSION
drwxr-xr-x 2 root   root   4096 Oct  4 06:03 bin
drwxr-xr-x 5 root   root   4096 Oct  4 06:03 venv
```
```
vscode ➜ ~/.local $ cat VERSION 
1.2.1
```
``` 
vscode ➜ ~/.local $ ls venv/
bin  include  lib  lib64  poetry_env  pyvenv.cfg
```

`~/.local/` 直下にある `VERSION` や `venv` はpoetry関連だと思うので、`/home/vscode/.local/pypoetry` などフォルダを掘って、そこにインストールするべきかな、と思っています。

従来通りユーザディレクトリに作るならpoetryのデフォルトの `~/.local/share/pypoetry` を使うか、CI recommendationになっている `/opt/poetry` のどちらかにしたいなと思っています。

- https://python-poetry.org/docs/#installing-with-the-official-installer:~:text=~/.local/share/pypoetry%20on%20Linux/Unix.
- https://python-poetry.org/docs/#ci-recommendations:~:text=export-,POETRY_HOME%3D/opt/poetry,-python3%20install%2Dpoetry

**Comment by ikanago** [comment]
デフォルトだし `~/.local/share/pypoetry` がいいかなと思います．
